"""initial
Revision ID: 1b0f96613ef5
Revises: 
Create Date: 2026-05-11 13:11:37.571240
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b0f96613ef5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadopedido',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('orden')
    )
    op.create_table('formapago',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('direccionentrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linea1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('linea2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cp', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productocategoria',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('productoingrediente',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('usuariorol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('asignado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['rol_codigo'], ['rol.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_codigo')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pago_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccionentrega.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estadopedido.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['formapago.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detallepedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre_snapshot', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('precio_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('personalizacion', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historialestadopedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_desde', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('estado_hasta', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['estado_desde'], ['estadopedido.codigo'], ),
    sa.ForeignKeyConstraint(['estado_hasta'], ['estadopedido.codigo'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('mp_payment_id', sa.Integer(), nullable=True),
    sa.Column('mp_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('mp_payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('historialestadopedido')
    op.drop_table('detallepedido')
    op.drop_table('pedido')
    op.drop_table('usuariorol')
    op.drop_table('refreshtoken')
    op.drop_table('productoingrediente')
    op.drop_table('productocategoria')
    op.drop_table('direccionentrega')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('producto')
    op.drop_table('ingrediente')
    op.drop_table('formapago')
    op.drop_table('estadopedido')
    op.drop_table('categoria')
    # ### end Alembic commands ###
