"""add address snapshot fields to pedido
Revision ID: 37879993625a
Revises: 1b0f96613ef5
Create Date: 2026-05-13 12:28:39.374638
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37879993625a'
down_revision: Union[str, None] = '1b0f96613ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('direccion_snapshot_alias', sa.String(length=50), nullable=True))
    op.add_column('pedido', sa.Column('direccion_snapshot_linea1', sa.String(length=255), nullable=True))
    op.add_column('pedido', sa.Column('direccion_snapshot_linea2', sa.String(length=255), nullable=True))
    op.add_column('pedido', sa.Column('direccion_snapshot_ciudad', sa.String(length=100), nullable=True))
    op.add_column('pedido', sa.Column('direccion_snapshot_cp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'direccion_snapshot_cp')
    op.drop_column('pedido', 'direccion_snapshot_ciudad')
    op.drop_column('pedido', 'direccion_snapshot_linea2')
    op.drop_column('pedido', 'direccion_snapshot_linea1')
    op.drop_column('pedido', 'direccion_snapshot_alias')
    # ### end Alembic commands ###
