"""add_activo_field_to_usuario
Revision ID: 54917d3bc8a2
Revises: 37879993625a
Create Date: 2026-05-13 15:01:31.044288
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54917d3bc8a2'
down_revision: Union[str, None] = '37879993625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('usuario', 'activo', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'activo')
    # ### end Alembic commands ###
