"""change mp_payment_id to string
Revision ID: 655d35decd98
Revises: 54917d3bc8a2
Create Date: 2026-05-13 21:20:53.539615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655d35decd98'
down_revision: Union[str, None] = '54917d3bc8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pago', 'mp_payment_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('pago_mp_payment_id_key'), 'pago', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pago_mp_payment_id_key'), 'pago', ['mp_payment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('pago', 'mp_payment_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
